#
# SystemAccount migration targets
---
honeybee.system_account::migration::event_source:
  active: true
  version_list_reader: honeybee.system_account::version_list::event_source::reader
  version_list_writer: honeybee.system_account::version_list::event_source::writer
  migration_loader:
    class: Honeybee\Infrastructure\Migration\FileSystemLoader
    directory: migration/couchdb

honeybee.system_account::migration::view_store:
  active: true
  version_list_reader: honeybee.system_account::version_list::view_store::reader
  version_list_writer: honeybee.system_account::version_list::view_store::writer
  index: honeybee-system_account
  target_connection: Default.ViewStore
  migration_loader:
    class: Honeybee\Infrastructure\Migration\FileSystemLoader
    directory: migration/elasticsearch
