#
# Specify config file to load using the ConfigLoader.
# The latter will load hierarchically starting at the app level and then traversing any registered crates,
# in the order they are specified within the crates.yml.
# Depending on the handler behavior concurring crate configs will be treated either as:
# firstone-wins, lastone-wins, flat-merge or deep-merge.
---
# the crates config is the only config that may only exist once within your project
# and that doesn't support hierarchical loading.
crates.yml:
  handler: Honeybee\FrameworkBinding\Silex\Config\Handler\CrateConfigHandler
  settings:
    parser: Symfony\Component\Yaml\Parser

# merge behaviour: lastone-wins
services.yml:
  handler: Honeybee\FrameworkBinding\Silex\Config\Handler\ServiceConfigHandler
  settings:
    parser: Symfony\Component\Yaml\Parser

# merge behaviour: lastone-wins
connections.yml:
  handler: Honeybee\FrameworkBinding\Silex\Config\Handler\ConnectionConfigHandler
  settings:
    parser: Symfony\Component\Yaml\Parser
