#
# Project level connection configuration.
---
view_store:
  class: Honeybee\Infrastructure\DataAccess\Connector\ElasticsearchConnector
  settings:
    transport: http
    host: localhost
    port: 9200
    index: honeylux.domain_events

msg_queue:
  class: Honeybee\Infrastructure\DataAccess\Connector\RabbitMqConnector
  settings:
    host: localhost
    port: 5762
    user: ${rabbitmq.user}
    password: ${rabbitmq.password}

mailer:
  class: Honeybee\Infrastructure\DataAccess\Connector\SwiftMailer\LocalSendmailConnector

mailer.null:
  class: Honeybee\Infrastructure\DataAccess\Connector\SwiftMailer\NullConnector

files.local:
  class: Honeybee\Infrastructure\DataAccess\Connector\Flysystem\LocalConnector
  settings:
    directory: ${project.dir}/data/files

files.local.tmp:
  class: Honeybee\Infrastructure\DataAccess\Connector\Flysystem\LocalConnector
  settings:
    directory: ${project.dir}/data/tmp_files

process_state.store:
  class: Honeybee\Infrastructure\DataAccess\Connector\Flysystem\LocalConnector
  settings:
    directory: ${project.dir}/data/process_states

process_state.cache:
  class: Honeybee\Infrastructure\DataAccess\Connector\Memory\ArrayConnector
