honeybee.environment:
  class: Honeybee\FrameworkBinding\Silex\Environment
  provisioner:
      class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\EnvironmentProvisioner

honeybee.template_renderer:
  class: Honeybee\Infrastructure\Template\Twig\TwigRenderer
  provisioner:
      class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\TemplateRendererProvisioner

#my.service:
#  class: My\Namespace\MyService
#  options: []
#  provisioner:
#    class: My\Namespace\MyServiceProvisioner
#    alias: My\Namespace\MyServiceInterface
#    share: true
#    settings:
#        base_url: http://api.example.com
#        verify_ssl: false

