#
# Honeylex core services
---
honeybee.environment:
  class: Honeybee\FrameworkBinding\Silex\Environment
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\EnvironmentProvisioner
    settings:
      alias: Honeybee\EnvironmentInterface

honeybee.infrastructure.template_renderer:
  class: Honeybee\Infrastructure\Template\Twig\TwigRenderer
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\TemplateRendererProvisioner
    settings:
      extensions:
        - Honeybee\FrameworkBinding\Silex\Twig\TwigExtension

honeybee.infrastructure.connector_service:
  class: Honeybee\Infrastructure\DataAccess\Connector\ConnectorService
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\ConnectorServiceProvisioner

honeybee.infrastructure.data_access_service:
  class: Honeybee\Infrastructure\DataAccess\DataAccessService
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\DataAccessServiceProvisioner

honeybee.infrastructure.migration_service:
  class: Honeybee\Infrastructure\Migration\MigrationService
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\MigrationServiceProvisioner

honeybee.infrastructure.expression_service:
  class: Honeybee\Infrastructure\Expression\ExpressionService
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\ExpressionServiceProvisioner

honeybee.infrastructure.event_bus:
  class: Honeybee\Infrastructure\Event\Bus\EventBus
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\EventBusProvisioner

honeybee.infrastructure.command_bus:
  class: Honeybee\Infrastructure\Command\Bus\CommandBus
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\CommandBusProvisioner
