honeybee.service_locator:
  class: Honeybee\ServiceLocator

honeybee.environment:
  class: Honeybee\FrameworkBinding\Silex\Environment

#my.service:
#  class: My\Namespace\MyService
#  options: []
#  provisioner:
#    class: My\Namespace\MyServiceProvisioner
#    alias: My\Namespace\MyServiceInterface
#    share: true
#    settings:
#        base_url: http://api.example.com
#        verify_ssl: false

