#
# honeylux core services
---
honeybee.environment:
  class: Honeybee\FrameworkBinding\Silex\Environment
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\EnvironmentProvisioner

honeybee.template_renderer:
  class: Honeybee\Infrastructure\Template\Twig\TwigRenderer
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\TemplateRendererProvisioner

# @todo continue with the connector-service
