#
# honeylux core services
---
honeybee.environment:
  class: Honeybee\FrameworkBinding\Silex\Environment
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\EnvironmentProvisioner

honeybee.template_renderer:
  class: Honeybee\Infrastructure\Template\Twig\TwigRenderer
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\TemplateRendererProvisioner

honeybee.infrastructure.connector_service:
  class: Honeybee\Infrastructure\DataAccess\Connector\ConnectorService
  provisioner:
    class: Honeybee\FrameworkBinding\Silex\Service\Provisioner\ConnectorServiceProvisioner

