#
# Project settings:
---
project:
  name: Honeylex
  description: 'Honeybee CQRS & ES integration with the Silex framework'
  app:
    prefix: honeylex
  database:
    prefix: honeylex
  email:
    from_email: honeylex@honeylex.dev
    from_name: Honeylex
  translation:
    default_locale: en
    locale_fallbacks: [ en, de ]
