en:
  messages:
    'Honeybee CQRS & ES integration with the Silex framework': 'Honeybee CQRS & ES integration with the Silex framework'
    'Welcome to your new application.': 'Welcome to your new application.'
  locale:
    'en': English
    'de': Deutsch

de:
  messages:
    'Honeybee CQRS & ES integration with the Silex framework': 'Honeybee CQRS & ES Integration mit dem Silex framework'
    'Welcome to your new application.': 'Willkommen in Ihrem neuen Anwendung.'